### ISSUE TITLE
Rest 协议：RpcContext.getContext().getRemoteHost()获取不到内容

### ISSUE THREAD

**Issue by Jason1220** [dangdangdotcom/dubbox#134]
想使用 Filter 过滤 IP 白名单，但发现使用 Rest 协议时，调用RpcContext.getContext().getRemoteHost()获取不到值，但使用 dubbo 协议可以，有人知道什么原因吗？难道RpcContext.getContext().getRemoteHost()不支持 Rest 协议吗？

**Comment by skysoul1985** [comment]
@Context
private HttpServletRequest httpRequest;
httpRequest.getRemoteAddr();

注入HttpServletRequest 可获取到

**Comment by li-shen** [comment]
详细看看文档 要获取到值需要特定的server实现 比如servlet 而且你的filter不能优先级过高

**Comment by Jason1220** [comment]
谢谢楼上两位的解答，此问题已经解决：
1、把 rest-server 从 Netty 换成 tomcat（）
2、扩展 Filter 接口
