### ISSUE TITLE
xsd文件没有修改吗?

### ISSUE THREAD

**Issue by meadlai** [dangdangdotcom/dubbox#20]
dubbo:protoco元素提示不允许属性:extension和optimizer

具体如下:

文件中的:
<dubbo:protocol name="dubbo" serialization="kryo" optimizer="com.alibaba.dubbo.demo.SerializationOptimizerImpl"/>
显示以下错误:
cvc-complex-type.3.2.2: Attribute 'optimizer' is not allowed to appear in element 'dubbo:protocol'.

======
 <dubbo:protocol name="rest" port="8888" threads="500" contextpath="services" server="tomcat" accepts="500"
                    extension="com.alibaba.dubbo.demo.extension.TraceInterceptor,
                    com.alibaba.dubbo.demo.extension.TraceFilter,
                    com.alibaba.dubbo.demo.extension.ClientTraceFilter,
                    com.alibaba.dubbo.demo.extension.DynamicTraceBinding,
                    com.alibaba.dubbo.demo.extension.CustomExceptionMapper,
                    com.alibaba.dubbo.rpc.protocol.rest.support.LoggingFilter"/>

显示以下错误:
cvc-complex-type.3.2.2: Attribute 'extension' is not allowed to appear in element 'dubbo:protocol'.

**Comment by li-shen** [comment]
用户操作有误

**Comment by VectorHo** [comment]
我也遇到这个问题
