### ISSUE TITLE
dubbox 2.8.4源代码拉出来用maven编译会出现异常

### ISSUE THREAD

**Issue by LouisLei** [dangdangdotcom/dubbox#203]
当用maven去编译dubbox2.8.4的时候，对于dubbox\dubbo-rpc\dubbo-rpc-hessian这个工程会出现异常：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project dubbo-rpc-hessian: Compilation failure
[ERROR] \git repository\dubbox\dubbo-rpc\dubbo-rpc-hessian\src\main\java\com\alibaba\dubbo\rpc\protocol\hessian\HttpClientConnection.java:[37,7] 错误: HttpClientConnection不是抽象的, 并且未覆盖HessianConnection中的抽象方法getContentEncoding()

**Comment by LouisLei** [comment]
异常时针对HttpClientConnection该类，经查阅HttpClientConnection实现的HessianConnection类确实有getContentEncoding()方法

**Comment by skymans** [comment]
dubbox 2.8.4 引用的是dubbo 2.8.4 ，所以编译的时候也要把github上面的代码下载下来，这是两个项目，怎么编译呢？

**Comment by LouisLei** [comment]
我是想把dubbox2.8.4重新打个包来自己用，所以就maven install了

**Comment by Xiaobaxi** [comment]
@LouisLei 这个应该是外部因素导致的吧，跟dubbo本身没有关系，我这边编译都是没有问题的

**Comment by LouisLei** [comment]
我来把maven的jdk版本改低点试试，我现在用的jdk1.8

**Comment by LouisLei** [comment]
找到问题了，这个要使用hession 4.0.7的版本才可以  ，版本高了就有这个问题了

**Comment by skymans** [comment]
我在编译的时候remoting-netty出错了，这个怎么回事呢，难道编译的时候需要开zookeeper服务？
[INFO] dubbo-remoting-netty .............................. FAILURE [1:39.559s]

**Comment by LouisLei** [comment]
不需要的，你看具体是报的什么异常出来的

**Comment by wangjia2016** [comment]
我用JDK1.7 也是各种POM报错，就没有一个不报错的。顺便问下，这个源码是用的jdk1.6还是1.7 我咋看是混搭呢

**Comment by LouisLei** [comment]
pom报错与jdk没有关系的   我用的1.7是可以的

**Comment by changwei0708** [comment]
1.7可以
