### ISSUE TITLE
Demo应用简单运行指南中的小错误

### ISSUE THREAD

**Issue by kazaff** [dangdangdotcom/dubbox#21]
[这里](http://dangdangdotcom.github.io/dubbox/demo.html)的倒数第三步提到的浏览器直接访问的链接，应该是由于代码更新导致的书写错误，正确地址应该是：

> http://127.0.0.1:8888/services/users/101.json

**Comment by li-shen** [comment]
是的，确实是个问题，很快会修复，谢谢！
