### ISSUE TITLE
Http调用Dubbox Rest服务，默认Jackson序列化

### ISSUE THREAD

**Issue by wxdh1987** [dangdangdotcom/dubbox#214]
如果json中多了实体不含的属性，老是报错org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field，原因是ResteasyJacksonProvider.readFrom构建的ObjectMapper缺少mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);这种配置，请问如何扩展

**Comment by wxdh1987** [comment]
另外Dubbo Rest协议，是不是只支持Jackson序列化，我配置了kryo没效果

**Comment by wxdh1987** [comment]
```
        <dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jackson2-provider</artifactId>
			<version>3.0.9.Final</version>
		</dependency>
```
解决问题，文档提供的jar包版本太低，缺少一些新特性。

**Comment by zhangyq1011** [comment]
个人感觉jackson2包的版本有点乱、搞不清楚
