### ISSUE TITLE
多个不同应用注册了相同服务，请检查{0}和{1}中是否有误暴露

### ISSUE THREAD

**Issue by misselvexu** [dangdangdotcom/dubbox#224]
这确定不是个小问题?

代码:index.vm
`
#set($providerApplication = "")    // 定义提供者的名称
#foreach($provider in $providers)

        // 为空,循环赋值 ;第二次不为空,不赋值 ;  下面的所有的 provider 都会出现警告
        #if ($providerApplication == "")
	         #set($providerApplication = $provider.application)
        #end

        #if($providerApplication != $provider.application)
               .....
               $i18n.get('warn')   // 显示异常警告
               .....
         #end

#end
`

移除判断$providerApplication== "" ;即可

**Comment by Johnson-Jia** [comment]
请问 这个文件在哪里啊？

**Comment by Johnson-Jia** [comment]
找到了  现在显示都正常了   感谢大神。。。

**Comment by huqing** [comment]
大神威武！ 2.5.6页没有修复c此BUG
搞了半天还以为是服务有问题
