### ISSUE TITLE
Dubbox should be on opentracing supported framework list

### ISSUE THREAD

**Issue by wu-sheng** [dangdangdotcom/dubbox#256]
As the only Chinese member of opentracing oragnization,  we have many supported frameworks, and supported tracers.

`Dubbox`, as an important rpc framework in China, I hope it can be on that list. Like other famous Chinese rpc framework have done, such as motan, hprose. 

If you want to join us, please let me know. 

If you know what you know what is OpenTracing? ref these two: http://opentracing.io and https://github.com/opentracing-contrib/opentracing-specification-zh

**Comment by Xiaobaxi** [comment]
@wu-sheng 我私下看能够支持一下

**Comment by wu-sheng** [comment]
通过filter支持应该不困难。主要是是否能合并到官方库中。

**Comment by Xiaobaxi** [comment]
@wu-sheng 是的，dubbox也很久没有人维护了

**Comment by wu-sheng** [comment]
不进去主版本，就不能算官方支持。没办法。
