### ISSUE TITLE
我看dubbo的pom里面依赖的Spring版本也已经是Spring3.x了

### ISSUE THREAD

**Issue by Liubey** [dangdangdotcom/dubbox#258]
https://github.com/alibaba/dubbo/blob/master/pom.xml
不知道是不是随便那么一升。

**Comment by www1350** [comment]
3.2.16.RELEASE

**Comment by Liubey** [comment]
对，master里面已经升级了，但是分支2.5.3里面还是2.X

**Comment by qinglo** [comment]
谢谢! 邮件已收到
