### ISSUE TITLE
这个报错是什么 运行demo的消费者 按照dubbo的方式启动dubbox启动不了

### ISSUE THREAD

**Issue by kuops** [dangdangdotcom/dubbox#273]
2017-03-22 16:24:03,035 [main] ERROR com.alibaba.dubbo.container.Main (Main.java:86) -  [DUBBO] Error creating bean with name 'com.alibaba.dubbo.demo.consumer.DemoAction#0' defined in URL [jar:file:/usr/local/dubbo-demo-consumer-2.8.4/lib/dubbo-demo-consumer-2.8.4.jar!/META-INF/spring/dubbo-demo-action.xml]: Cannot resolve reference to bean 'bidService' while setting bean property 'bidService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bidService': FactoryBean threw exception on object creation; nested exception is org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 5000, dubbo version: 2.8.4, current host: 127.0.0.1

================================
版本2.8.4
```
[root@OS6-node1 dubbo-demo-consumer]# grep -v "#" /usr/local/dubbo-demo-consumer/conf/dubbo.properties 
dubbo.container=log4j,spring
dubbo.application.name=demo-consumer
dubbo.application.owner=
dubbo.registry.address=zookeeper://10.0.0.130:2181
dubbo.monitor.protocol=registry
dubbo.log4j.file=logs/dubbo-demo-consumer.log
dubbo.log4j.level=WARN
```
#执行这个命令报错的
dubbo-demo-consumer/bin/start.sh

**Comment by yunhaibin** [comment]
错误里面提示很清楚，dubbo服务连不上Zookeeper注册中心

**Comment by yunhaibin** [comment]
建议你可以在dubbo服务的本机上起一个Zookeeper服务，直接连本机看一下是否可以，如果本机能连上Zookeeper注册中心，那就在网络上找找问题，可以用telnet或者nc等检查一下网络链路是否通着

**Comment by kuops** [comment]
注册中心 提供者 和管理中心连接都是正常的，这个是只是消费者上面报错 zookeeper 的配置文件我下面已经贴出来的 是正确的，我很确定，所有的都检查了没问题

**Comment by yunhaibin** [comment]
我们是在xml里面配置的，你可以参考一下
<dubbo:registry protocol="zookeeper" address="172.16.137.196:2491,172.16.137.197:2491,172.16.137.198:2491" file="${user.home}/.dubbo/${dubbo.registry.file}"/>
如果不行就启动服务以后，看一下网络连接

**Comment by kuops** [comment]
示例消费者安装
(+) (#)

安装:

wget http://code.alibabatech.com/mvn/releases/com/alibaba/dubbo-demo-consumer/2.4.1/dubbo-demo-consumer-2.4.1-assembly.tar.gz
tar zxvf dubbo-demo-consumer-2.4.1-assembly.tar.gz
cd dubbo-demo-consumer-2.4.1
配置:

vi conf/dubbo.properties
启动:

./bin/start.sh
tail -f logs/stdout.log
停止:

./bin/stop.sh
重启:

./bin/restart.sh
调试:

./bin/start.sh debug
系统状态:

./bin/dump.sh
总控入口:

./bin/server.sh start
./bin/server.sh stop
./bin/server.sh restart
./bin/server.sh debug
./bin/server.sh dump
标准输出:

tail -f logs/stdout.log


我用的是淘宝的2.5.x的方式安装的消费者。 

你们的部署demo

用IDE运行/dubbo-demo/dubbo-demo-provider/.../test目录下的DemoProvider启动dubbo服务端，目前他会分别启动dubbo协议（包括用kryo和FST序列化）和REST协议的服务
用IDE运行/dubbo-demo/dubbo-demo-consumer/.../test目录下的DemoConsumer来启动dubbo客户端调用上面的服务端，直接看console的输出即可
用IDE运行/dubbo-demo/dubbo-demo-consumer/.../test目录下的RestClient来启动rest客户端（模拟非dubbo的rest客户端）调用上面的服务端，直接看console的输出即可



我都没有找到test在哪里，跟淘宝的解压出来不一样。dubbo-demo-consumer-2.8.4-assembly.tar.gz
就是这个包，用法和淘宝的不一样吗？不是修改  conf/dubbo.properties吗

**Comment by yunhaibin** [comment]
我用的是当当的dubbox的示例

**Comment by kuops** [comment]
我是个运维，看不懂开发的IDE

**Comment by zjmeixinyanzhi** [comment]
我也遇到了同样的问题，不知道楼上最后怎么解决的

**Comment by qinglo** [comment]
谢谢! 邮件已收到
