### ISSUE TITLE
给monitor设计提个建议

### ISSUE THREAD

**Issue by mjaow** [dangdangdotcom/dubbox#280]
很多公司在使用dubbo的时候会很重视monitor，但是现在simple-monitor统计的东西太粗略，比如平均rt，非常不精确。很多时候没办法定位问题。

- 建议加上统计rt分布的功能，比如抽样收集1000个rt，算出99%的在哪个区间，90%的在哪个区间，这样对系统监控能力更清晰

**Comment by kimmking** [comment]
monitor可以提出来100个improvement，
其实关键是
1、最好把它从dubbo的core里独立出来，
2、单独找一帮人来维护类似monitor这种生态必须的工具。

问题是，现在dubbo的维护都非常乏力，monitor更没人来搞。
