### ISSUE TITLE
ReaderInterceptor不起作用

### ISSUE THREAD

**Issue by kazaff** [dangdangdotcom/dubbox#30]
~~~java
@Priority(Priorities.USER)
public class DemoInterceptor implements ReaderInterceptor, WriterInterceptor {

    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException, WebApplicationException {
        System.out.println("Reader interceptor invoked");

        return context.proceed();
    }

    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        System.out.println("Writer interceptor invoked");
        context.proceed();
    }
}
~~~

按照官方例子，却发现`ReaderInterceptor`不起作用，只打印出"Writer interceptor invoked"，断点也无法捕获在对应位置，可以证明确实是没有调用。

请问如何解决？

**Comment by kazaff** [comment]
> 这个bug还没空来看？你跑过demo吗，demo里面难道也调用不到？--- by @li-shen  from QQ

是的，也调不到，我追源码，restprotocol是把extend的值统一交给RESTEasy框架来管理，应该是靠后者来实现jax-rs规范吧？也就是说问题不在dubbox，而是要从RESTEasy下手吧？

**Comment by kazaff** [comment]
经过我自己的测试，发现单独使用resteasy，最新版本下也存在这个问题，不过目前看来，更换成官方提供的preInterceptor是可以满足要求的，具体细节还需要看一下resteasy源码。周一见

**Comment by li-shen** [comment]
我看了一下，这个不是bug。在不需要做反序列化的比如get场景，reader inteceptor肯定就不会被调用。

**Comment by li-shen** [comment]
我看了一下，这个不是bug。在不需要做反序列化的比如get场景，reader inteceptor肯定就不会被调用。

**Comment by kazaff** [comment]
那如果做认证的话，就不能用这个拦截器了~

**Comment by li-shen** [comment]
用filter吧，不用interceptor。另外dubbo自己也有filter
