### ISSUE TITLE
关于REST合并到DUBBO主干的提议

### ISSUE THREAD

**Issue by Authorlove** [dangdangdotcom/dubbox#371]
目前dubbo正在并将长期维护中，非常希望合并dubbo其他分支的优秀功能。REST的功能是优先级比较高的需求，考虑到
1. dubbox的rest实现很完善，文档全面，并且有生产环境的检验，稳定性有保障
2. 使用dubbox的rest功能的用户较多，可以平滑迁移

希望可以先将rest的功能合并到dubbo主干，希望得到dubbox作者（@li-shen）支持 ：
https://github.com/alibaba/dubbo/pull/917

**Comment by B0B02333** [comment]
支持这个

**Comment by hongbailan** [comment]
支持

**Comment by bamboolsu** [comment]
支持， 目前进行的怎么样了？ 预计何时能合并过来

**Comment by xusheng1987** [comment]
最新的dubbo2.6.0已经合并了
