### ISSUE TITLE
dubbo项目报错：cvc-complex-type.2.4.c

### ISSUE THREAD

**Issue by jmszwzr** [dangdangdotcom/dubbox#374]
1、git下载了dangdangdotcom/dubbox整个仓库，本地编译成功
![Dubbo安装成功-01](https://i.loli.net/2017/12/22/5a3cb7abce7c6.png)
![Dubbo安装成功-02](https://i.loli.net/2017/12/22/5a3cb82621dcb.png)
2、引入三个项目dubbo-st-api/dubbo-st-consumer/dubbo-st-provider的时候，spring文件报错：`cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'dubbo:application'.	dubbo-st-consumer.xml	/dubbo-st-consumer/src/main/resources/META-INF/spring	line 8	XML Problem`
![引入三个项目后报错信息](https://i.loli.net/2017/12/22/5a3cb869cfdbe.png)
---
想学习使用当当网的Dubbox的Rest风格远程调用，还请大牛帮忙看看，谢谢啦！

**Comment by collerwang** [comment]
你好，我也出现了这个情况，但是我一开始用的myeclipse2014就没有这个情况，后来不知道为什么报错了我就换了eclipse4.4，这时候就报这个错了，你试试换个开发工具

**Comment by qinglo** [comment]
谢谢! 邮件已收到
