### ISSUE TITLE
dubbox是否在rest协议的基础上增加ip白名单功能

### ISSUE THREAD

**Issue by yuanwhy** [dangdangdotcom/dubbox#48]
rest协议在跨语言的情况下，不能走注册中心，所以也不能使用dubbo的令牌验证功能，安全和OAuth在未来会加到dubbox中，那么目前有没有在开发中呢；是不是加个ip白名单的功能会更快

**Comment by li-shen** [comment]
目前你自己用filter实现白名单就行了
