### ISSUE TITLE
Dubbox服务被多次调用

### ISSUE THREAD

**Issue by kisChang** [dangdangdotcom/dubbox#68]
通过Dubbox调用一个服务时，出现服务被多次调用的问题（出现的几率很低。出现时一般是调用两次，有时会被调用三次，然后返回最后一次调用的结果）
我可以通过什么方式去调试问题的原因？

Dubbox 版本：2.8.4
Zookeeper版本：3.4.6  standalone
Ubuntu14.04
java version "1.7.0_75"

**Comment by afredlyj** [comment]
触发了dubbo的重试机制？

**Comment by orika** [comment]
触发了dubbo的重试机制，类似这种接口要考虑幂等性，不然很容易重复调用

**Comment by liuwawa** [comment]
去看看dubbo的文档，有个接口超时重试，默认3次，如果你不想超时重试，设置成0就行了

**Comment by kisChang** [comment]
恩，估计是这个问题（但是在单机上还出现接口调用超时，很难想象）。
先谢过各位了，这两天没时间测试，先关闭issue，后面测试到还有这个问题再开
