### ISSUE TITLE
如何自定义rest的时间格式序列化？

### ISSUE THREAD

**Issue by kimmking** [dangdangdotcom/dubbox#71]
貌似，从resteasy到jackson这一串都写死了。

这里有个绕道的办法，http://www.4byte.cn/question/448870/changing-default-json-time-format-with-resteasy-3-x.html

**Comment by kimmking** [comment]
已搞定，通过extension。

**Comment by java-my-life** [comment]
@kimmking 请问如何搞定的
能具体说一下吗？
extension里面具体怎么操作？
