### ISSUE TITLE
使用dubbox-admin打包编译后war启动报错

### ISSUE THREAD

**Issue by coolworker** [dangdangdotcom/dubbox#72]
38 java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Wed Dec 30 21:41:29 CST 2015]; root of context hierar>
 39   at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
 40   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
 41   at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869)
 42   at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836)
 43   at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579)
 44   at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115)
 45   at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4980)
 46   at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5626)
 47   at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
 48   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
 49   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
 50   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
 51   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
 52   at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
 53   at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
 54   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
 55   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
 56   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 57   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 58   at java.lang.Thread.run(Thread.java:744)
 59 2015-12-30 21:41:29,186 [localhost-startStop-1] WARN  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:880) - Exception thrown from LifecycleProcessor on context close
dubbo-governance.log  Line:16/395[4%]Col:1Buf:#1[9][0x9]
337   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
338   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
339   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
340   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
341   at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
342   at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
343   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
344   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
345   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
346   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
347   at java.lang.Thread.run(Thread.java:744)
348 Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]
349   at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:141)
350   at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:330)
351   ... 25 more
352 2015-12-30 22:01:06,227 [localhost-startStop-1] INFO  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:862) - Closing Root WebApplicationContext: startup date [Wed Dec 30 22:01:06 CST 20>
353 2015-12-30 22:01:06,237 [localhost-startStop-1] WARN  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:872) - Exception thrown from ApplicationListener handling ContextClosedEvent
354 java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Wed Dec 30 22:01:06 CST 2015]; root of context hierar>
355   at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
356   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
357   at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869)
358   at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836)
359   at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579)
360   at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115)
361   at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4980)
362   at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5626)
363   at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
364   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
365   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
366   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
367   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
368   at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
369   at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
370   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
371   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
372   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
373   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
374   at java.lang.Thread.run(Thread.java:744)
375 2015-12-30 22:01:06,239 [localhost-startStop-1] WARN  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:880) - Exception thrown from LifecycleProcessor on context close
376 java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: Root WebApplicationContext: startup date [Wed Dec 30 22:01:06 CST 2015]; root of context hierarchy
377   at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:357)
378   at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877)
379   at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836)
380   at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579)
381   at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115)
382   at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4980)
383   at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5626)
384   at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
385   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
386   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
387   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
388   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
389   at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
390   at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
391   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
392   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
393   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
394   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
395   at java.lang.Thread.run(Thread.java:744)

**Comment by coolworker** [comment]
已经解决由于spring-web的版本过高导致，对dubbo－admin降低spring－web版本即可

**Comment by cookier** [comment]
@coolworker 
请问是降低至什么版本呢？我现在用的是4.2。降了好几个版本都不行。
特别蛋疼，直接运行dubbox提供的demo-admin.war一直提示没有找到applicationContext.xml

**Comment by cookier** [comment]
spring恢复成3.2.9.RELEASE，重新部署demo-admin项目后就可以了。。。

**Comment by yunwenlong** [comment]
这点真坑啊。
