### ISSUE TITLE
how to config the path in zookeeper?

### ISSUE THREAD

**Issue by Hackerline** [dangdangdotcom/dubbox#80]
I want to change the path in zookeeper /dubbo/....
but how to config it ?

**Comment by kimmking** [comment]
<dubbo:registry address="zookeeper://127.0.0.1:2181" group=" the path you want"/>
such as <dubbo:registry address="zookeeper://127.0.0.1:2181" group="payway"/>

**Comment by Hackerline** [comment]
@kimmking thx

**Comment by cc4dogman** [comment]
thxs
