### ISSUE TITLE
bug AtomicPositiveInteger hashCode equals 

### ISSUE THREAD

**Issue by sdcuike** [dangdangdotcom/dubbox#83]
发现了一个bug，请看：https://github.com/alibaba/dubbo/pull/183

阿里那边一直没回应，来这里试试。

代码变化之处：https://github.com/alibaba/dubbo/pull/183/files

**Comment by kimmking** [comment]
explain why this is a bug first and show a testcase to reproduce it

**Comment by sdcuike** [comment]
阿里那边已经修复https://github.com/alibaba/dubbo/pull/183
