### ISSUE TITLE
LinkedHashMap序列化遇到问题

### ISSUE THREAD

**Issue by iceray** [dangdangdotcom/dubbox#91]
我使用DUBBO来序列化，当LIinkedHashMap达到一定的数量的时候，返回的数据就GET不到了，请问这个是个BUG吗？

**Comment by Lihuanghe** [comment]
应该不算bug，所有rpc对调用参数序列化后的体积都有限制的，太大了对服务器内存和网络消耗很大。
改造你们业务接口吧。

**Comment by iceray** [comment]
好的，谢谢

**Comment by kimmking** [comment]
不应该啊，有testcase吗

**Comment by iceray** [comment]
谢谢两位，是我这边的问题
