### ISSUE TITLE
KYRO序列化问题咨询

### ISSUE THREAD

**Issue by iceray** [dangdangdotcom/dubbox#92]
请问我使用KRYO进行序列化的时候，我有一个自己定义的PRODUCT对象，但是使用KYRO进行序列化的时候，就报出了下面这个EXCEPTION,：
com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 183, Size: 1|Serialization trace:|backCam (xxx.xxx.product.bean.Product)<|java.io.IOException: com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 183, Size: 1|Serialization trace:|backCam (xxx.xxxx.product.bean.Product)<|?at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectInput.readObject(KryoObjectInput.java:127)<|?at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectInput.readObject(KryoObjectInput.java:140)<|?at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectInput.readObject(KryoObjectInput.java:151)<|?at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:87)<|?at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:117)<|?at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:98)<|?at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:134)<|?at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:95)<|?at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)<|?at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:134)<|?at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)<|?at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)<|?at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)<|?at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)<|?at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)<|?at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)<|?at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)<|?at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)<|?at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)<|?at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)<|?at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)<|?at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)<|?at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<|?at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<|?at java.lang.Thread.run(Thread.java:745)<|Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 183, Size: 1|Serialization trace:|backCam (xxx.xxxx.product.bean.Product)<|?at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)<|?at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)<|?at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)<|?at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectInput.readObject(KryoObjectInput.java:125)<|?... 24 more<|Caused by: java.lang.IndexOutOfBoundsException: Index: 183, Size: 1<|?at java.util.ArrayList.rangeCheck(ArrayList.java:653)<|?at java.util.ArrayList.get(ArrayList.java:429)<|?at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)<|?at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:834)<|?at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:757)<|?at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)<|?... 27 more<|

我使用的PRODUCT对象，都是一些基本的类型，像这些：
public class Product implements Serializable {

    private Integer id;         

    private String brand;               

   
    private Float price;             

    private Date time;        

    private String desc;           

    private Boolean hasGps;            
配置我也按照DEOM进行了配置：

dubbo:protocol name="dubbo" serialization="dubbo" optimizer="xxx.xxx.common.SerializationOptimizerImpl"

也有注册这个类：
public class SerializationOptimizerImpl implements SerializationOptimizer {

    @Override
    public Collection<Class> getSerializableClasses() {
        List<Class> classes = new ArrayList<>();
        classes.add(Product.class);
        return classes;
    }
}

请问是不是我这边写错了什么呢？

**Comment by kimmking** [comment]
提供一个testcase吧

**Comment by PepperYan** [comment]
same bug here, 我找了很久, 最后把各个序列化对象的list的顺序理成一样, 就不报错了. 你可以试试.

**Comment by dimmacro** [comment]
这是kryo序列化的特点，要求服务端和消费端必须对注册的class顺序一样，即getSerializableClasses返回的LinkList对add的bean顺序要一致。因为kryo为了压缩序列化数据，传输的类信息是数字，如果两边顺序不一样，同一数字在两边对应的类不一样，自然会报错。

**Comment by iceray** [comment]
谢谢各位了，感激不尽

**Comment by LuckyLYB** [comment]
如果项目中同时使用kryo和java原生的序列化方式，dubbo 配置两个protocol，注册的接口通过version来区分，但是实际上走的还是java原生的，并没有走kryo，是什么原因呢？
